alpha_multiplier: 1.0
backup_entropy: false
batch_size: 256
bc_steps: 0
buffer_size: 10000000
checkpoints_path: /home/server/Desktop/sebastiano/checkpoints/CQL-antmaze-large-play-v2-be4e3cf8
cql_alpha: 5.0
cql_clip_diff_max: .inf
cql_clip_diff_min: -200.0
cql_importance_sample: true
cql_lagrange: true
cql_max_target_backup: true
cql_n_actions: 10
cql_target_action_gap: 0.8
cql_temp: 1.0
device: cuda
discount: 0.99
env: antmaze-large-play-v2
eval_freq: 50000
group: cql-antmaze-large-play-v2-multiseed-v0
load_model: ''
max_timesteps: 1000000
n_episodes: 100
name: CQL-antmaze-large-play-v2-be4e3cf8
normalize: false
normalize_reward: true
orthogonal_init: true
policy_log_std_multiplier: 1.0
policy_lr: 0.0001
project: CORL
q_n_hidden_layers: 5
qf_lr: 0.0003
reward_bias: -5.0
reward_scale: 10.0
seed: 0
soft_target_update_rate: 0.005
target_update_period: 1
use_automatic_entropy_tuning: true
